### ISSUE TITLE
Not working in Openhab 2.0

### ISSUE THREAD

**Issue by billmans** [mikenemat/org.openhab.binding.plum#4] opened 2016-11-08 17:48 UTC
Trying to get this working in openHAB 2.0.

I have used the 1.x compat mode and I still can't seem to get it too work.  From what I can see it could be this, and require a simple fix....?

http://www.mkyong.com/java/the-type-defaulthttpclient-is-deprecated/

This is a great plugin, the only for working with Plum lightpads, would love to get this working in openHAB 2.0.

**Comment by mikenemat** [comment] 2016-11-08 18:34
Hi,

I'm hoping I can spare some time this weekend to download OpenHAB 2.0 and fix this, along with some other issues reported in GitHub which I've unfortunately had to neglect for the past few months. I'm hesitant to commit a fix without testing it on a copy of OpenHAB 2.0 myself. I'll do my best to get this sorted out on the weekend.

Thanks for the positive feedback.

**Comment by billmans** [comment] 2016-11-08 18:47
Thanks - that would be fantastic. I was excited to see somebody had done something with the plum light pads!

I am currently playing with eclipse to see what I could do, but I think this is above me! ;-)

Thanks

**Comment by mikenemat** [comment] 2016-11-14 00:41
Hi,

I'm running an OpenHAB 2.0 Developer environment right now, and the Plum binding seems to work just fine without changes. However, it is entirely plausible that a deployed version of OpenHAB 2.0 differs from the developer environment. I will try that next.

In the mean time, can you attach any log files from OpenHAB 2.x which indicated errors with the Plum binding? That might help point me in the right direction.

**Comment by mikenemat** [comment] 2016-11-14 01:37
Looks like you were right, it is the httpclient. Very strange that would work in a developer environment and not a deployed package. I'll get that fixed now.

**Comment by billmans** [comment] 2016-11-14 01:43
Let me know if you have an updated jar, I will give it a try!  Have everything up an running in 2.0 except plum (which is the main reason I started looking at openhab!)

Thanks for creating this, and updating!

**Comment by mikenemat** [comment] 2016-11-14 02:39
Fixed. Added new OpenHAB 2 compatible JAR in the target folder. Tested it on a clean OpenHAB 2.0 install, as well as verified backwards compatibility with OpenHAB 1.8.x and 1.9.x :)

Please note that various new libraries used in this have not been load tested. I have ran the old version without issues for months. If stability issues are found in the new library, please report them and I will do my best to fix them ASAP.

**Closed by mikenemat** 2016-11-14 02:39 UTC

**Comment by billmans** [comment] 2017-12-13 03:25
Hi Mike,
Most seems to be working well, I have had some issues where I seem to lose control of a switch and I am seeing the following in the log.  Can't make it happen, or figure out if its even related yet.  Will keep an eye open.  (there are a few other strange things with 2.2 that might not be plum related)
B



22:21:09.642 [ERROR] [penhab.binding.plum.PlumActiveBinding] - Plum HTTP Request to IP 10.0.1.26 returned ERROR null
22:21:09.644 [ERROR] [ab.core.service.AbstractActiveService] - Error while executing background thread Plum
java.lang.NullPointerException: null
	at org.openhab.binding.plum.PlumActiveBinding.execute(PlumActiveBinding.java:281) [247:org.openhab.binding.plum:1.11.0.201712110223]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:144) [216:org.openhab.core.compat1x:2.2.0.201712090925]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:166) [216:org.openhab.core.compat1x:2.2.0.201712090925]

**Comment by mikenemat** [comment] 2017-12-13 03:28
Seeing something similar on one of mine ....I should be able to reproduce it and sort it out. I’ll keep you in the loop. Very odd error.

**Comment by mikenemat** [comment] 2017-12-13 04:11
Bill, seems like this issue is two sides of the same coin.

I managed to reproduce it with one of my lightpads which is on the network (responding to pings) but timing out for HTTP connections. I also can't control it via the Plum app, nor via the testing curl command I use:

curl -k -H "User-Agent: Plum/2.3.0 (iPhone; iOS 9.2.1; Scale/2.00)" -H "X-Plum-House-Access-Token: `echo -n HOUSE_ACCESS_TOKEN | sha256sum | cut -d " " -f 1`" -H "Content-type: application/json"  https://PLUM_LIGHTPAD_IP:8443/v2/getLogicalLoadMetrics/ -d '{"llid":"PLUM_LIGHTPAD_LOGICAL_LOAD_ID"}' -v --connect-timeout 5

I'm going to issue another build shortly with some updated error feedback to make it clear this is a timeout. Beyond that....try the lightpad via the plum app, and if it indeed doesn't work as I suspect, reboot the lightpad (via breaker or air gap) and see if it goes away.

**Comment by mikenemat** [comment] 2017-12-13 04:23
New build. Cleaned up logging a bit more and made timeouts obvious. Also got rid of the TCP Stream events in the log. You can still see them if you start OpenHAB in debug mode, but INFO-level was too noisy. They are DEBUG level now. 

https://github.com/mikenemat/org.openhab.binding.plum/blob/master/target/org.openhab.binding.plum-1.11.0-OPENHAB_2_0.jar

**Comment by mikenemat** [comment] 2017-12-13 04:43
Hard rebooting my lightpad that was giving me the same error you were seeing fixed the issue. It was definitely an issue with the lightpad, not the plugin.
